### ISSUE TITLE
Item border sclaing issue

### ISSUE THREAD

**Issue by LootFever** [AcidWeb/ElvUI-AdiBags#1]
When you change the scale, the border around the items "breaks".
It just doesn't show some border lines.

Example for 80% scaling:
![image](https://user-images.githubusercontent.com/32418486/42782147-597cdd2c-8948-11e8-8d19-9fd9422c41ab.png)

**Comment by AcidWeb** [comment]
Working as intended. 1px borders require pixel-perfect UI.

BTW I'm not maintaining this fork anymore.
